FROM stackci/node:6

EXPOSE 80

MAINTAINER Jonathan Dunlap  <jdunlap@outlook.com>

ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    SQSD_MAX_MESSAGES_PER_REQUEST=$SQSD_MAX_MESSAGES_PER_REQUEST \
    SQSD_QUEUE_REGION_NAME=$SQSD_QUEUE_REGION_NAME \
    SQSD_QUEUE_URL=$SQSD_QUEUE_URL \
    SQSD_MAX_REQUESTS=$SQSD_MAX_REQUESTS \
    SQSD_RUN_DAEMONIZED=$SQSD_RUN_DAEMONIZED \
    SQSD_SLEEP_SECONDS=$SQSD_SLEEP_SECONDS \
    SQSD_WAIT_TIME_SECONDS=$SQSD_WAIT_TIME_SECONDS \
    SQSD_WORKER_HTTP_URL=$SQSD_WORKER_HTTP_URL \
    SQSD_WORKER_HTTP_REQUEST_CONTENT_TYPE=$SQSD_WORKER_HTTP_REQUEST_CONTENT_TYPE \
    SQSD_WORKER_CONCURRENCY=$SQSD_WORKER_CONCURRENCY \
    SQSD_WORKER_TIMEOUT=$SQSD_WORKER_TIMEOUT \
    SQSD_WORKER_HEALTH_URL=$SQSD_WORKER_HEALTH_URL \
    SQSD_WORKER_HEALTH_WAIT_TIME=$SQSD_WORKER_HEALTH_WAIT_TIME \
    SQSD_VERBOSE=$SQSD_VERBOSE

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./package.json .
RUN npm install --production

COPY . .
RUN chmod u+x ./start.sh
# Run sqsd

ENTRYPOINT []
CMD ["./start.sh"]
